service: bga-history-to-slack

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1

functions:
  check:
    handler: handler.check
    events:
      - schedule: rate(5 minutes)
    environment:
      GAME_NAME: ""
      SLACK_WEBHOOK_URL: ""
      TABLE_ID: ""
      NOTIFY_MINUTES: "5"