// from https://x.boardgamearena.net/data/themereleases/220420-1001/js/modules/nls/ja/lang_sevenwonders-20220428.js
export const LANG_MAP: {[key in string]: string} = {
    "${card_name}: ${player_name} gets ${coin} coins": "${player_name}は${card_name}から${coin}コインを得た",
    "${leftCost} to ${leftPlayer}": "${leftPlayer}へ${leftCost}コイン",
    "${player_name} (force ${force}) wins the conflict against ${player_name2} (force ${force2}) and gets ${points} points": "${player_name}(盾${force})は${player_name2}(盾${force2})に交戦で勝利し、+${points}ポイントの勝利トークン1個を得た",
    "${player_name} build a Wonder step ${with}": "${player_name}は七不思議の一段階を建造した${with}",
    "${player_name} build a Wonder step for ${coin} coins ${with}": "${player_name}は${coin}コインで七不思議の一段階を建造した${with}",
    "${player_name} copy ${guild} with The Statue of Zeus in Olympia (${points} additional points).": "${player_name}はオリンピアのゼウス像の効果で${guild}をコピーした(${points}ポイントを追加で得点)",
    "${player_name} discards a card to get 3 coins": "${player_name}はカードを捨てて3コインを得た",
    "${player_name} gets an extra Science Symbol: ${symbol}": "${player_name}は追加の科学シンボルを得た: ${symbol}",
    "${player_name} plays ${card_name} ${with}": "${player_name}は${card_name}を建造した${with}",
    "${player_name} plays ${card_name} ${with} (chained with ${original_building})": "${player_name}は${card_name}を建造した${with} (${original_building}から連鎖)",
    "${player_name} plays ${card_name} for ${coin} coin(s) ${with}": "${player_name}は${coin}コインで${card_name}を建造した${with}",
    "${player_name} plays ${card_name} using Statue of Zeus power (age ${age})": "${player_name}は${card_name}をオリンピアのゼウス像の効果で建造した(世代${age})",
    "${player_name} plays ${card_name} using Statue of Zeus power (first card of Age)": "${player_name}はオリンピアのゼウス像の効果(段階1)を使用して、${card_name}を無償で建造した",
    "${player_name} plays ${card_name} using Statue of Zeus power (first card of a color)": "${player_name}はオリンピアのゼウス像の効果(段階2)を使用して、${card_name}を無償で建造した",
    "${player_name} plays ${card_name} using Statue of Zeus power (last card of Age)": "${player_name}はオリンピアのゼウス像の効果(段階2)を使用して、${card_name}を無償で建造した",
    "${wonder_name}: ${player_name} gains ${coin} coins": "${player_name}は${wonder_name}から${coin}コインを得た",
    "${you} must choose a Wonder side": "${you}は七不思議ボードの使用する面を選んでください",
    "Academy": "学園",
    "Age ${age} starts!": "第${age}世代の開始!",
    "Age ${age}: ${you} must choose a card to play": "第${age}世代: ${you}はカードを1枚プレイしてください",
    "Age ${age}: Some players must choose a card to play": "第${age}世代: プレイヤーはカードを1枚プレイしてください",
    "Age I": "第I世代",
    "Age II": "第II世代",
    "Age III": "第III世代",
    "Altar": "祭壇",
    "Amount of coins": "コインの数",
    "Apothocary": "薬屋",
    "Aqueduct": "水道橋",
    "Archery Range": "矢場",
    "Arena": "闘技場",
    "Arsenal": "武器庫",
    "As the leader of one of the great 7 cities of the ancient world, you must carefully gather resources, develop commercial routes, and affirm your military supremacy.": "古代世界の7大都市の一つのリーダーとして、慎重に資源を集め、商業ルートを開発し、軍事的優位性を維持しなければなりません。",
    "At the end of the game, you get one additional science symbol of your choice": "ゲーム終了時、科学シンボル1つを追加で得る",
    "Available coins": "コイン",
    "Barracks": "兵舎",
    "Baths": "浴場",
    "Bazaar": "バザー",
    "Brickyard": "レンガ工場",
    "Build your city and erect an architectural wonder which will transcend future times!": "あなたの街を築き、未来を超越した建築の奇跡を起こしましょう!",
    "Build your wonder": "七不思議の建造",
    "Builders Guild": "建業者ギルド",
    "Buy ${ress} to ${player} for ${cost}": "${ress}を${player}から${cost}で購入",
    "Can build for free:": "次の世代で無償で建造できる建造物:",
    "Caravansery": "隊商宿",
    "Card list": "カードリストと連鎖",
    "Card played: Civilian": "市民建造物",
    "Card played: Commerce": "商業建造物",
    "Card played: Guild": "ギルド",
    "Card played: Manufactured Goods": "製造物",
    "Card played: Military": "軍事建造物",
    "Card played: Raw material": "原材料",
    "Card played: Science": "科学建造物",
    "Cards rotation": "手札の移動方向",
    "Castrum": "砦",
    "Chained building: You have the pre-required building to play this Wonder step": "建造の連鎖: あなたは七不思議の現段階を無償で建造するのに必要な建造物を所有しています",
    "Chained building: You have the pre-required building to play this card": "建造の連鎖: あなたはこの建造物を無償で建造するのに必要な建造物を所有しています",
    "Chamber of Commerce": "商工会議所",
    "Choose": "選択",
    "Choose how to pay ${card}:": "${card}のプレイ方法を選んでください:",
    "Choose this face": "この面を選ぶ",
    "Circus": "競技場",
    "Civilian Structure": "市民建造物",
    "Clay": "粘土",
    "Clay Pit": "粘土採取場",
    "Clay Pool": "粘土置き場",
    "Cog": "機構",
    "Coin": "コイン",
    "Coins gained on commerce": "取引で得たコイン",
    "Coins spent on commerce": "取引で支払ったコイン",
    "Commercial Structure": "商業建造物",
    "Compass": "幾何学",
    "Cost": "コスト",
    "Courthouse": "裁判所",
    "Craftsmen Guild": "職人ギルド",
    "Decorators Guild": "装飾者ギルド",
    "Discard pile": "捨て札置き場",
    "Discard this card": "このカードを捨てる",
    "Discarded cards number": "捨てられたカード",
    "Discarding actions": "カードを捨てた数",
    "Dispensary": "診療所",
    "East Trading Post": "東方交易場",
    "End of game": "ゲーム終了",
    "Excavation": "開削",
    "Final military force": "盾",
    "Final scores": "勝利ポイント",
    "Forest Cave": "森の洞窟",
    "Fortifications": "要塞",
    "Forum": "広場",
    "Foundry": "鋳造所",
    "Free chained build": "連鎖で建造した建造物",
    "Gardens": "庭園",
    "Glass": "ガラス",
    "Glassworks": "ガラス工房",
    "Guard Tower": "櫓",
    "Guild": "ギルド",
    "Haven": "港",
    "I dont want to": "建造しない",
    "IMPORTANT: the Guild points are reevaluated as if YOU own it, so these points may differ from the points your opponent gets from the same guild.": "重要事項: ギルドによる勝利ポイントは、あなたが所有しているものとして計算されます。そのため、コピー元のギルドを所有しているプレイヤーと獲得勝利ポイントが異なる場合があります。",
    "Laboratory": "研究所",
    "Library": "図書館",
    "Lighthouse": "灯台",
    "Lodge": "ロッジ",
    "Loom": "織機",
    "Ludus": "試合場",
    "Lumber Yard": "材木置き場",
    "Magistrates Guild": "行政官ギルド",
    "Manufactured Good": "製造物",
    "Marketplace": "市場",
    "Military Structure": "軍事建造物",
    "Military defeat: -1 VP": "敗戦トークン: -1VP",
    "Military victory (age I): +1 VP": "勝利トークン(世代I): +1VP",
    "Military victory (age II): +3 VP": "勝利トークン(世代II): +3VP",
    "Military victory (age III): +5 VP": "勝利トークン(世代III): +5VP",
    "Mine": "鉱山",
    "No one wins the conflict between ${player_name} and ${player_name2} (force ${force})": "${player_name}と${player_name2}との交戦は勝者なし(互いに${force}盾)",
    "Note: Board Game Arena is choosing the best guild for you automatically.": "注意: ボードゲームアリーナでは、勝利ポイントが最も多くなるように自動的に選択されます。",
    "Note: Board Game Arena is choosing the best symbol for you automatically.": "注意: 勝利ポイントが最も多くなるように、自動的に科学シンボルが選択されます。",
    "Number of turns": "ターン数",
    "Observatory": "天文台",
    "Once per Age, you can build any card for free": "各世代に1度、建造物を無償で建造できる",
    "Ore": "鉱石",
    "Ore Vein": "鉱脈",
    "Palace": "宮殿",
    "Pantheon": "神殿",
    "Papyrus": "パピルス",
    "Pawnshop": "質屋",
    "Philosophers Guild": "哲学者ギルド",
    "Pick a card from discarded pile a build it for free (see discarded pile size at the bottom of the page)": "捨て札置き場からカードを1枚選び、選んだ建造物を無償で建造できる",
    "Play for free with Zeus": "ゼウス像の効果で無償でプレイ",
    "Play this card": "このカードをプレイ",
    "Points: Civilian buildings": "市民建造物からのVP",
    "Points: Commerce buildings": "商業建造物からのVP",
    "Points: Guilds": "ギルドからのVP",
    "Points: Science buildings": "科学建造物からのVP",
    "Points: Wonder": "七不思議からのVP",
    "Points: conflicts defeats": "軍事交戦からのVP(敗北)",
    "Points: conflicts victories": "軍事交戦からのVP(勝利)",
    "Points: remaining coins": "残りコインからのVP",
    "Press": "製紙場",
    "Provide": "生成",
    "Provide all the following": "次のものをすべて生成",
    "Provide one of the following": "次のもののうち1つを生成",
    "Quarry": "石切場",
    "Raw Material": "原材料",
    "Sawmill": "製材所",
    "School": "学校",
    "Science provides 7 points per set of 3 different symbols + NxN points for each serie of N identical symbols.": "異なる3種類のシンボル1つずつのセット1つにつき、勝利ポイント7点 + 各種類ごとに、シンボルN個につきNxNポイントを得る。",
    "Scientific Structure": "科学建造物",
    "Scientists Guild": "科学者ギルド",
    "Scores": "得点",
    "Scriptorium": "写字室",
    "Senate": "元老院",
    "Shields": "盾",
    "Shipowners Guild": "船主ギルド",
    "Siege Workshop": "兵器開発所",
    "Some players choose a Wonder side": "プレイヤーは七不思議の面を選んでください",
    "Sorry, but no players has discarded any cards until now: you cannot use your power.": "すみません、まだ誰も今までカードを捨てていないのでこの能力を使うことはできません。",
    "Spies Guild": "密偵ギルド",
    "Stables": "厩",
    "Stage": "段階",
    "Statue": "彫像",
    "Statue of Zeus: You can play for free the first card of each Age": "ゼウス像: あなたは1枚目の世代カードを無償で建造できます",
    "Statue of Zeus: You can play for free the first card of each color": "ゼウス像: あなたはカードの各色について最初の世代カードを無償で建造できます",
    "Statue of Zeus: You can play for free the last card of each Age": "ゼウス像: あなたは最後(6枚目)の世代カードを無償で建造できます",
    "Stockade": "営倉",
    "Stone": "石材",
    "Stone Pit": "採石場",
    "Strategists Guild": "戦略家ギルド",
    "Study": "研究室",
    "Tablet": "文字",
    "Tavern": "酒場",
    "Temple": "寺院",
    "The Colossus of Rhodes": "ロードスの巨人像",
    "The Hanging Gardens of Babylon": "バビロンの空中庭園",
    "The Hanging Gardens: ${actplayer} may play his last card": "空中庭園: ${actplayer}は最後のカードをプレイできます",
    "The Hanging Gardens: ${you} may play your last card": "空中庭園: ${you}は最後のカードをプレイできます",
    "The Lighthouse of Alexandria": "アレクサンドリアの灯台",
    "The Mausoleum of Halicarnassus": "ハリカルナッソスのマウソロス霊廟",
    "The Mausoleum: ${actplayer} may pick a card from discard pile": "マウソロス霊廟: ${actplayer}は捨て札置き場からカード1枚を無償で建造できます",
    "The Mausoleum: ${you} may pick a card from discard pile": "マウソロス霊廟: ${you}は捨て札置き場からカード1枚を無償で建造できます",
    "The Pyramids of Giza": "ギザのピラミッド",
    "The Statue of Zeus in Olympia": "オリンピアのゼウス像",
    "The Temple of Artemis in Ephesus": "エファソスのアルテミス神殿",
    "The hand of cards is passed to the player sitting clockwise": "手札は時計回りに移動します",
    "The hand of cards is passed to the player sitting counter-clockwise": "手札は反時計回りに移動します",
    "The most awarded strategy board game: more than 30 gaming awards. 7 Wonders is a card drafting game that is played using three decks of cards featuring depictions of ancient civilizations.": "最も受賞した戦略ボードゲーム：30以上のゲーム賞。 世界の七不思議は、古代文明を描写した3組のカードを使用してプレイされるカードドラフトゲームです。",
    "Theater": "劇場",
    "There are no more stages to build on your Wonder": "あなたの七不思議の建造段階はもうありません",
    "Timber Yard": "貯木場",
    "Town Hall": "公会堂",
    "Traders Guild": "商人ギルド",
    "Training Ground": "訓練場",
    "Tree Farm": "植林地",
    "University": "大学",
    "Victory points": "勝利ポイント",
    "Vineyard": "ブドウ園",
    "Walls": "防壁",
    "West Trading Post": "西方交易場",
    "Wonder face A": "七不思議A面",
    "Wonder id": "七不思議番号",
    "Wonder steps built": "七不思議の一段階の建造",
    "Wood": "木材",
    "Workers Guild": "労働者ギルド",
    "Workshop": "工房",
    "You can build for free the first card of each Age": "1枚目の世代カードを無償で建造できる",
    "You can build for free the first card of each color": "カードの各色について、最初のカードを無償で建造できる",
    "You can build for free the last card of each Age": "最後(6枚目)の世代カードを無償で建造できる",
    "You can copy a guild built by one of your neighbours": "両隣の都市が建造したギルドから1つを選び、得点計算時にそのギルドを自分で建造したかのように扱う",
    "You do not have the needed resources to play this Wonder step": "あなたは七不思議の現段階の建造に必要な資源を持っていません",
    "You do not have the needed resources to play this card": "あなたはこの建造物の建造に必要な資源を持っていません",
    "You don't have enough resources (or coins) to pay this card": "このカードをプレイするのに必要な資源(もしくはコイン)が足りません",
    "You don't have enough resources to build this Wonder step": "七不思議の現段階の建造に必要な資源が足りません",
    "You draft cards over multiple rounds, carefully building towards long-term goals.": "カードを複数のラウンドでドラフトし、長期的な目標に向けて慎重に構築します。",
    "You have the needed resources to play this Wonder step": "あなたは七不思議の現段階の建造に必要な資源を持っています",
    "You have the needed resources to play this card": "あなたはこの建造物の建造に必要な資源を持っています",
    "You may buy resources to your neighbours to play this Wonder step": "七不思議の現段階の建造に必要な資源を両隣の都市から購入できます",
    "You may buy resources to your neighbours to play this card": "この建造物の建造に必要な資源を両隣の都市から購入できます",
    "You may play your 7th card instead of discarding it": "7枚目の世代カードを捨て札にせずにプレイできる",
    "You must choose a card from the discard pile, not from your hand": "あなたは捨て札の中からカードを1枚選んでください(あなたの手札からではありません)",
    "You pay only 1 coin when you buy a ${resource} from ${directions}": "${directions}から${resource}を1つにつき1コインで購入できる",
    "brown, gray and purple": "茶色、灰色、紫色のカード",
    "buying ${ress} to ${player} for ${cost}": "${ress}を${player}から${cost}で購入",
    "by ${trades}": ": ${trades}",
    "civilian": "市民",
    "commerce": "商業",
    "conflict": "軍事交戦",
    "defeat token": "敗戦トークン",
    "guild": "ギルド",
    "in the city on your left": "あなたの右隣の都市",
    "in the city on your right": "あなたの左隣の都市",
    "in the neighboring cities": "(両隣の都市にあるもの)",
    "in the neighboring cities AND in your own city": "(両隣の都市および自分の都市のもの)",
    "in your own city": "(自分の都市にあるもの)",
    "or for free with:": "次の建造物から無償の建造が可能:",
    "science": "科学",
    "sevenwonders_displayed": "世界の七不思議(7 Wonders)",
    "to ${rightPlayer} ${rightCost}": "${rightPlayer}へ${rightCost}コイン",
    "treasure": "宝",
    "wonder": "七不思議",
    "wonder stage built": "完成した七不思議の段階",
    "wonder with all stages": "七不思議のすべての段階が完成している場合",
    "your left neighbour": "左隣のプレイヤー",
    "your neighbours": "両隣のプレイヤー",
    "your right neighbour": "右隣のプレイヤー",
    "your wonder step": "七不思議の段階",
    "dummy": "dummy"
};
